---
name: Mac-Apps-Seasonality-Constants
version: 1.000002
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Define various constants relating to Seasonality (http://gauchosoft.com/Software/Seasonality/).
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Env: 0
  Exporter: 0
  Readonly: 0
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
build_requires:
  Test::More: 0
dynamic_config: 1
provides:
  Mac::Apps::Seasonality::Constants:
    file: lib/Mac/Apps/Seasonality/Constants.pm
    version: 1.000002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
